[package]
name = "ross-logger"
version = "0.1.0"
authors = ["Linas Nikiperaviƒçius <linas@linasdev.com>"]
edition = "2018"
license-file = "LICENSE.md"
description = "Logger for the Rusty Old Smart System"
repository = "https://github.com/linasdev/ross-logger"
readme = "README.md"

[dependencies]
